[tox]
envlist = python
minversion = 3.4.0
requires =
    setuptools >= 40.9.0
    pip >= 19.0.3
isolated_build = true

[testenv:build-dists]
basepython = python3
isolated_build = true
usedevelop = false
skip_install = true
ignore_outcome=true
deps =
    build
setenv =
    PYPI_UPLOAD = true
commands =
    rm -rfv {toxinidir}/dist/ {toxinidir}/build/
    {envpython} -m build
allowlist_externals =
    rm